[package]
name = "vsr_simulation"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.10.1"
clap = { version = "4.5.41", features = ["derive"] }
dashmap = "6.1.0"
rand = "0.9.1"
rand_chacha = "0.9.0"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
vsr = { path = "../core" }
